SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DVM002](
	[AFU_PROJET] [varchar](10) NOT NULL CONSTRAINT [DVM002_AFU_PROJET_DF]  DEFAULT ('          '),
	[AFU_VERSAO] [varchar](4) NOT NULL CONSTRAINT [DVM002_AFU_VERSAO_DF]  DEFAULT ('    '),
	[AFU_TAREFA] [varchar](12) NOT NULL CONSTRAINT [DVM002_AFU_TAREFA_DF]  DEFAULT ('            '),
	[AFU_RECURS] [varchar](15) NOT NULL CONSTRAINT [DVM002_AFU_RECURS_DF]  DEFAULT ('               '),
	[AFU_DATA] [varchar](8) NOT NULL CONSTRAINT [DVM002_AFU_DATA_DF]  DEFAULT ('        '),
	[AFU_HORAI] [varchar](5) NOT NULL CONSTRAINT [DVM002_AFU_HORAI_DF]  DEFAULT ('     '),
	[AFU_HORAF] [varchar](5) NOT NULL CONSTRAINT [DVM002_AFU_HORAF_DF]  DEFAULT ('     '),
	[D_E_L_E_T_] [varchar](1) NOT NULL CONSTRAINT [DVM002_D_E_L_E_T__DF]  DEFAULT (' '),
	[R_E_C_N_O_] [int] NOT NULL CONSTRAINT [DVM002_R_E_C_N_O__DF]  DEFAULT ((0)),
 CONSTRAINT [DVM002_PK] PRIMARY KEY CLUSTERED 
(
	[R_E_C_N_O_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF